/*
 * ADC_cfg.h
 *
 *  Created on: Dec 16, 2019
 *      Author: DELL
 */

#ifndef ADC_CFG_H_
#define ADC_CFG_H_

//SINGLE OR AUTOTRIGGER
#define ADC_MODE ADC_MODE_AUTOTRIGGER
//AUTOTRIGGER SOURCE
#define ADC_AUTOTRIGGERSOURCE ADC_AUTOTRIGGERSOURCE_FRUN
//2,4,8,16,32,64,128
#define ADC_PRESCALAR ADC_PRESCALAR_128
//8 OR 10
#define ADC_BITS ADC_BITS_sBIT
//AVCC OR INTERNAL(2.56)
#define ADC_REF ADC_REF_AVCC


#endif /* ADC_CFG_H_ */
